### ISSUE TITLE
Problems with temporary presences

### ISSUE THREAD

**Issue by ACertainCoder** [PreMiD/Extension#10]
OS: Windows 10 64-Bit (Latest version)
Browser: Firefox 73.0.1 (64-Bit)

![grafik](https://user-images.githubusercontent.com/47316898/75113318-359a5a00-564d-11ea-9936-0f607956a7dc.png)
I pressed shift to load a created presence and it said that it's already loading a presence - I could load mine tho, which was quiet strange.
But it became more strange after I restarted Firefox to remove the temporary presence. It was still there! I used the removal-tool from the extension to get rid of it and then every single presence was gone. The store doesn't work correctly anymore. Only a reinstallation of the extention fixed it again.

Just wanted to report it because it's really annoying to reinstall the extension over and over again just to get your presence when it got released on the store.

**Comment by Bas950** [comment]
@ACertainCoder I have the issue aswell, just restart the app xD

**Comment by ACertainCoder** [comment]
🤔 I've done that after you told me. I closed Firefox and restarted the app. Unfortunately the temp presence was still loaded after i reopened the browser.

**Comment by Bas950** [comment]
hmm, I just close the app and instantly its gone 🤔

**Comment by ACertainCoder** [comment]
¯\_(ツ)_/¯ I also tried closing Firefox & PreMiD, opening Firefox (while PreMiD is still closed). The presence was still there. I closed Firefox again, ran PreMiD and opened Firefox another time - still the same.

**Comment by Timeraa** [comment]
That was an issue with a translation that someone changed...
