### ISSUE TITLE
Aniflix automatic Presence activation Bug

### ISSUE THREAD

**Issue by LordiAniflix** [PreMiD/Extension#188]
**Is your bug request related to a problem? Please describe.**

Aniflix is partnered with Premid so the presence is automatically added when you open the page but due to special circumstances it should be disabled on my system. 
I have tried to turn it off but every time I go to the site or click on a new Episode it is back on again.
![premid 1](https://user-images.githubusercontent.com/46389324/129428736-295ecf23-90b4-4872-ad85-f0bac7dfbc1f.png)

**Describe the solution you'd like**

A Button that can deactivate the "Automatic Presence Activation" 
![premid 2](https://user-images.githubusercontent.com/46389324/129428739-73073358-9caa-4901-a1f1-e1b94db6516d.png)

**Describe alternatives you've considered**
-

**Additional context**

Google Chrome
Version 92.0.4515.131 (Official Build) (64-Bit)
Windows 10 Version 21H1 for x64-based Systems
Premid Extension 2.2.3
PreMid Application 2.2.0
Screen 1 is the problems Picture
Screen 2 is the solution Picture

**Comment by EncryptedDev** [comment]
This will be taken into account through the development of V3
