### ISSUE TITLE
Suggestion: Extension features

### ISSUE THREAD

**Issue by BigFlubba** [PreMiD/Extension#189]
I would like for an option in the extension to allow when you click on your profile you can switch which Discord client it is hooked into. I run more than one client at a time and it gets a bit frustrating trying to get which client it goes through. I know this would benefit a lot of users like me who use more than one client at a time.

Another feature I would like to suggest is, I would like the feature to have an option on depending on which discord account is hooked into the extension all presences for that account would be enabled, and if you switch to another account the presence settings and the ones enabled for that account would change according to each account.
Example: 
Discord account: user1234#0001
Presence's enabled: Youtube and Netflix
Settings: Youtube- privacy mode and show timestamps
Netflix- privacy mode

Discord account: user4567#0002
Presence's enabled: Reddit
Settings: Reddit: N/A

I would like for a 'profile' to be made per Discord account. I understand that many users only have one account but some have more than one and others have a family computer that they use and they use more than one account one on one computer.

Final suggestion: Option to export your settings and installed presence's to a file and enable cloud save or save with Chrome sync.
I recently had to reinstall a fresh version of Windows and When I added all my things back (yes I have chrome sync fully enabled) it did not have my presence's or settings synced. I had to add everything back manually. It would be great if this process had some form of automation.

I'm open to questions or anything.

**Comment by EncryptedDev** [comment]
As far as I'm aware, this is not possible due to Discord limitations 
> I would like for an option in the extension to allow when you click on your profile you can switch which Discord client it is hooked into. I run more than one client at a time and it gets a bit frustrating trying to get which client it goes through. I know this would benefit a lot of users like me who use more than one client at a time.

**Comment by TheHunter1234** [comment]
How? In what way?

**Comment by EncryptedDev** [comment]
Discord only open one port for RPC I believe, so you can't have two of the same ports open on one computer

**Comment by TheHunter1234** [comment]
Interesting. Something to look into for sure.

**Comment by EncryptedDev** [comment]
It will be looked into during V3 Development
