### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by foxt** [PreMiD/Extension#231]
Hello, I'm using the Premid extension (2.2.3) with the BBC provider on Firefox (105.0.3), and I noticed that the video was chugging and one of my CPU cores was pinned at 100%, after looking at the inspector it seems the `getPageletiable` function in the Premid extension is the issue. 

In a 4.7s profile, the getPageletiable function was blocking the thread for 3.1s, being called over 3000 times.

https://profiler.firefox.com/public/azmxap2haf0g2j50nbdmxkvgy6z1zeyz2ffpff8/calltree/?globalTrackOrder=01&implementation=js&localTrackOrderByPid=87451-0~87503-0&thread=1&v=7

**Comment by EncryptedDev** [comment]
Should be fixed in v2.5
