### ISSUE TITLE
FEATURE REQUEST: A clear button for statuses

### ISSUE THREAD

**Issue by Razor7100** [PreMiD/Extension#247]
**Is your feature request related to a problem? Please describe.**
there's this annoying bug I have where songs I've listened to stuck on my profile when there's nothing to display like I have nothing open, and I'm sure other users have a problem where their status sticks too on other sites

**Describe the solution you'd like**
this clears out the users premid status so it doesn't show on the profile, like a reset/refresh button

**Describe alternatives you've considered**
I haven't thought about any really

**Additional context**
None

**Comment by Timeraa** [comment]
Not possible for us to add but we are fixing this issue another way
