### ISSUE TITLE
PreMiD shows closed service after suspend

### ISSUE THREAD

**Issue by OokamiTheLord** [PreMiD/Extension#26]
After suspending PC and waking it up with browser open, if there is no PreMiD service open, PreMiD reports the last known one, usually, one that is closed. 

Workaround for this is to open one of PreMiD services, wait for the status to change to it, and then close it. Then PreMiD returns back to normal.

**Comment by kawakaami** [comment]
Not PreMiD issue nor extension. It is probably because discord has broken RPCServer and it is trying to reconnect/or closed when you suspend.

**Comment by OokamiTheLord** [comment]
It usually shows service which was already closed before I suspended my PC, and what fixes it is restart of browser, or opening another service and closing it, so it really looks like it's something between extension and PreMiD. Restarting PreMiD or Discord should help if it would be problem on the Discord / RPCServer side6 sie 2020 12:56 kawakami <notifications@github.com> napisał(a):
Not PreMiD issue nor extension. It is probably because discord has broken RPCServer and it is trying to reconnect/or closed when you suspend.

**Comment by naomiuwu** [comment]
Maybe it will be fixed soon in new version.
