### ISSUE TITLE
Add own presence permantly to PreMiD

### ISSUE THREAD

**Issue by Rassez** [PreMiD/Extension#27]
**Is your feature request related to a problem? Please describe.**
No, it's not problem. I must always add my presence manually to PreMiD.

**Describe the solution you'd like**
I think best idea is, you can add owns presences permantly to the PreMiD. Example me, i don't want share my own presence for all users. I only want use it.

**Describe alternatives you've considered**
Some button where you can add your own presence. You can choose your presence, and load it.

**Additional context**
Nope, i don't have. I would be happy if this were possible.
Thanks!

**Comment by Bas950** [comment]
Make it to TMP presences will always stay untill you remove it with trashcan, and that you can load mulitple at once.

**Comment by TehRamsus** [comment]
@Bas950 Sorry, but that not works. If i example restart pc, thats TPM disappears.

**Comment by Bas950** [comment]
> @Bas950 Sorry, but that not works. If i example restart pc, thats TPM disappears.

Nah that was a note to our devs on how they should make it work.

**Comment by TehRamsus** [comment]
Aaah sorry. But okey! Thanks to answer!

**Comment by Timeraa** [comment]
Will be changed in v3.

**Comment by kawakami** [comment]
As Tim said, but not on release but a little time later.
