### ISSUE TITLE
Don't send identifier to science API endpoint

### ISSUE THREAD

**Issue by CanadaHonk** [PreMiD/Extension#31]

**Comment by Oj18** [comment]
Update: Why does the identifier exist at all if not to "track" people, it seems useless. Been told it's to prevent spam / bots but the identifier can be literally any string: https://github.com/PreMiD/API/blob/master/src/endpoints/v2/science.ts#L8

**Comment by Timeraa** [comment]
Our API and most of PreMiD are open source, we have the identifier which is just a random Id, which is used to "track" what presences are used and which operating system, it does not include any data that we could use to figure out who you are, in fact it's only purpose rn is to make the Presence store a bit more sorted as it's sorted by Presence usage. We will consider collecting the data in a better way but we never have the intention to track anyone.
