### ISSUE TITLE
Weird bug/glitch

### ISSUE THREAD

**Issue by Helaqrow** [PreMiD/Extension#35]
Hi, I was asked to send my issue here. I recently switched from Chrome to Microsoft Edge, I added my presences in and went on my day. After a few days, I went to see if my discord is showing Webtoon but it didn't, I went and looked at the extension to find all my added presences were removed and just the default ones are left. I added them back though but it is just really weird to suddenly get all my presences removed.

**Comment by kawakaami** [comment]
Not a bug nor glitch, probably something broke on your end.

**Comment by Timeraa** [comment]
Closing this as I can't reproduce it (main dev use edge as my daily driver). v3 should fix this issue if it is one.
