### ISSUE TITLE
Mozilla Addons "Store"

### ISSUE THREAD

**Issue by xdhmoore** [PreMiD/Extension#54]
Looking over PreMiD for the first time. It looks pretty awesome. I'm curious though why the extension doesn't seem to be on https://addons.mozilla.org. It does seem to be on the Chrome store. I thought release versions of Firefox now would only install addons.mozilla.org-hosted XPIs, but actually it looks like I'm wrong. You can get signed and be self-hosted. Still, I'm curious why not on the Firefox store? I usually feel more hesitant to install extensions from other places.

**Comment by ririxichan** [comment]
Hey, as I remember Mozzila Firefox Store doesn't allow extensions that injecting something to website (in this case presence).

**Comment by fr0r** [comment]
additional context: as what ririxi said, yeah, firefox doesn't like us on the store, but they allow us to sign our extension and self-host it (which is something we do since our removal)

**Comment by xdhmoore** [comment]
Thanks for the info. I think that answers my question.
