### ISSUE TITLE
Safari / MacOS extension 

### ISSUE THREAD

**Issue by BaileyJM02** [PreMiD/Extension#55]
So, I haven't looked much into how this would be done within the project but it might be an idea to implement PreMiD into a MacOS extension so you can update Discord whether I'm using Bear to write my notes or on looking at the App Store etc. 

A Safari extension to allow for website presence is also a nice idea...

**Comment by furkanalptokac** [comment]
i'm waiting for safari extension.

**Comment by NoaHimesaka1873** [comment]
Tried porting the extension with safari-web-extension-converter and it compiles and installs, but it can't communicate with the website. So it's no for right now.

**Comment by ririxichan** [comment]
Good to know! We will do more tests and changes in v3 do it will work fully. Thanks 😄

**Comment by MysteryCoder456** [comment]
> Why would you use Safari anyways? Just get a _good_ Browser like Chrome or Edge

did you really just say Chrome is good?

**Comment by ririxichan** [comment]
Okay, if you want to argue go to another place for now you are doing post unrelated to issue so please, go somewhere else or talk about issue itself.

**Comment by MysteryCoder456** [comment]
> At WWDC, Apple announced a way to really easily port Chrome extensions to Safari. I'd be pretty excited to see a Safari extension.

that would be pretty cool, I've never heard of it though.

**Comment by ririxidev** [comment]
If someone is smart enough to build it, check this: https://github.com/ririxidev/premid-extension-safari. Works only with xcode 12 :)

**Comment by ririxidev** [comment]
@SpaceN64 it's already a thing. Just go to https://premid.app/downloads and you will find Safari button to download extension
