### ISSUE TITLE
Trying to load this in Opera - Error: Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by CarlyRaeJepsenStan** [PreMiD/Extension#73]
I downloaded this repository, unpacked the .zip archive, and then tried to load it in Opera by using "load unpacked" (developer mode in the extensions page active).  Several errors were found:
1. The manifest.json is located in /assets, while it should be in /.  I manually moved it to /, so I could load the extension.
2. The icon paths all pointed to assets/images, instead of src/assets/images.
3. ["Default locale was specified, but _locales subtree is missing"](https://stackoverflow.com/questions/12993034/chrome-extension-manifest-version-2-locales-issues).  I simply commented out the default locale line. 
4. the file "js/vendor.js" was marked as missing.  Strangely enough, the entire js folder was not there. 

At this point my coding knowledge failed me, and I wasn't able fix any more.

 Please fix these in a future update!

**Comment by ririxichan** [comment]
Why did you download repository? It isnt for just downloading. Extension for firefox and chrome is on site. It is in assets and it is right place for it but you didnt build it with webpack. So please close this or ocntact us on discord if you want more details (discord.premid.app)

**Comment by CarlyRaeJepsenStan** [comment]
@ririxichan I just updated the issue.  The Install Chrome Extensions extension no longer functions correctly on opera.

**Comment by ririxichan** [comment]
Read my comment carefuly.

**Comment by CarlyRaeJepsenStan** [comment]
Huh, alright.
