### ISSUE TITLE
Settings are not added to localStorage until they are changed

### ISSUE THREAD

**Issue by strafe** [PreMiD/Extension#76]
Seems like per-presence settings don't get set in localStorage until they are toggled. This results in `getSettings` throwing a bunch of errors on sites like Twitch if you've never adjusted the settings, and no presence is displayed.

https://github.com/PreMiD/Extension/blob/release/src/util/presence/devHelper.ts#L174-L199

**Comment by ririxichan** [comment]
Already fixed, will appear in new update

**Comment by Bas950** [comment]
Already fixed in upcoming release, we are almost ready to release it, for now use: https://media.discordapp.net/attachments/526736087377248257/735934633706913812/PresenceSettings.gif

**Comment by Bas950** [comment]
![](https://docs.premid.app/presencesettings.gif)
