### ISSUE TITLE
Game priority over PreMiD

### ISSUE THREAD

**Issue by foxboy6412** [PreMiD/Extension#83]
I would like to be able to have my game status show up over my web activity because i listen to Soundcloud while playing games a lot and PreMiD displays instead of the game I'm playing. I would prefer to have the game displayed first, maybe make this toggleable?

**Comment by ririxidev** [comment]
Discord decides about priority and when it overtakes games etc. You amd Us can't do anything about it. Please next time check Rich Presence documentation before asking these questions.
