### ISSUE TITLE
RPC hides itself after changing to another Tab with the Brave Browser

### ISSUE THREAD

**Issue by CyCodeDE** [PreMiD/Extension#86]
**Describe the bug**
When changing the focused Tab, the RPC hides itself after a few seconds. Happens only with Brave. Works fine with Chrome and Firefox.

**To Reproduce**
1. Open the site of any corresponding presence
2. wait for the RPC to appear
3. change your Tab to any other Website
4. wait a few seconds
5. the RPC will disappear

**Expected behavior**
The RPC should stay when changing the Tab.

**Desktop:**
 - OS: Linux (Arch)
 - Browser: Brave
 - Version: 2.2.0.6 but also happens with 2.1.0

**Additional Information**
Developer Console does not print anything.
Backend Program says following when changing to another Tab: 

> Clear all activity
> Create RPC client
> Destroy RPC client

**Comment by ririxidev** [comment]
Brave is broken with our extension since they do some things for "privacy" so we can't fix it. You should ask brave developers how to fix and report bug, not to us.

**Comment by Bas950** [comment]
1. Open the site of any corresponding presence
2. wait for the RPC to appear
3. change your Tab to any other Website
4. wait a few seconds
5. the RPC will disappear

This is also kind of intended behavior, since we show the status for the tab you are currently one, so if you go to another tab that doesn't have a presence supported, it will stop showing.

**Comment by CyCodeDE** [comment]
@Bas950 that does not really make sense with YouTube and YouTube Music and other Video/Music Streaming Services (I have only tested YouTube and YouTube Music).

**Comment by Bas950** [comment]
> @Bas950 that does not really make sense with YouTube and YouTube Music and other Video/Music Streaming Services (I have only tested YouTube and YouTube Music).

then your error probs has to do with the brave browser since other users dont have this :/

**Comment by ririxidev** [comment]
Like I said, Brave browser is doing some "shit" things for privacy and brakes a lot of functions of normal chromium so :/
