### ISSUE TITLE
Showing strings instead of proper English

### ISSUE THREAD

**Issue by MCPE-PC** [PreMiD/Extension#97]
Tried disabling AdGuard
![1](https://user-images.githubusercontent.com/20432839/104103914-303b1200-52e8-11eb-9885-61be71753c12.png)
![2](https://user-images.githubusercontent.com/20432839/104103922-34672f80-52e8-11eb-8747-4a551677217f.png)

**Comment by Bas950** [comment]
We currently have a bug with Korean, Japanese and Chinese browser languages, if you change to English or to any other and then reinstall the extension, it should be fixed. We are working on a fix to make it work again for the currently broken browser languages.

For updates on when it's fixed please join our [Support Discord Server](https://discord.premid.app/).
